# The name of the application (no spaces)
app_name: speciminer

# A brief description of the app.
description: Finds occurrences of USNM specimens in the scientific literature

# Your first and last name
user: Adam Mansur

# Your email
email: mansura@si.edu

# The primary language the application is written in - will be used for installing dependencies
# Current options are Python, R, and Go
language: Python

# You can choose to specify a list of dictionaries, a list of terms, or both.
# If both dictionaries and terms are provided, all terms in the dictionary PLUS
# all listed terms will be used
terms: [usnm, nmnh]
